settings:
  title: 'bracy.dev Status Page'
  url: 'https://status.bracy.dev' # used for Slack & Discord messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: false # experimental feature, enable only for <5 monitors or on paid plans

  # configurable texts across the status page
  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: 'Some checks failed'

# list of monitors
monitors:
  - id: bracy.dev # unique identifier
    name: bracy.dev
    description: 'bracy.dev main site' # default=empty
    url: 'https://bracy.dev/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # should the titles be links to the service, default=true
  - id: notes.bracy.dev # unique identifier
    name: notes.bracy.dev
    description: 'bracy.dev notes site' # default=empty
    url: 'https://notes.bracy.dev/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # should the titles be links to the service, default=true
